# Generated by Django 5.1.1 on 2024-10-03 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('rating', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(upload_to=None)),
                ('created_since', models.DateField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=512)),
                ('user_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraging_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('home_address', models.CharField(max_length=254)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (9, 'Other')])),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foraging_app.user')),
            ],
        ),
    ]
