# Generated by Django 5.1.1 on 2024-10-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_app', '0002_alter_user_managers_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
