# Generated by Django 5.1.1 on 2024-12-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_app', '0002_alter_species_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
