# Generated by Django 5.1.1 on 2024-10-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_app', '0003_remove_user_profile_email_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
